### ISSUE TITLE
feat: allow using existing IAM Role

### ISSUE THREAD

**Issue by reegnz** [lacework/terraform-aws-eks-audit-log#11]
# Feature Request

**Describe the Feature Request**
In other lacework terraform modules ([terraform-aws-ecr](https://github.com/lacework/terraform-aws-ecr/blob/main/main.tf#L16), [terraform-aws-config](https://github.com/lacework/terraform-aws-config/blob/main/main.tf#L17)) you have the option to bring your own IAM Role.
This module should also allow for that.

**Describe Preferred Solution**
Make the iam role module optional:
* introduce `use_existing_iam_role` flag
* introduce `iam_role_arn`, `iam_role_name`, `iam_role_external_id` variables to pass in existing role details.

**Comment by dmurray-lacework** [comment]
Hey @reegnz, thank you for raising this. For consistency across our modules we'll take a look at this.

**Comment by rmoles** [comment]
Hi @reegnz. Thanks for raising this.
Currently this module creates 3 IAM roles:
- Lacework cross account role
- Firehose role
- Cloudwatch log role
Would you be able to clarify whether the ask is to enable end users to use an existing IAM role in place of the Lacework cross account role, or replace all 3 roles with IAM role(s)?

**Comment by reegnz** [comment]
I'd be fine with just reusing an existing role for the cross account role, like in the other lacework modules.

**Comment by dmurray-lacework** [comment]
Looks like was completed here: https://github.com/lacework/terraform-aws-eks-audit-log/pull/13

I think this can be closed

**Comment by afiune** [comment]
Closing as per previous comment, please feel free to reopen.
